import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Navbar from "./ui/navbar/Navbar";
import { Recursive } from "next/font/google";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={recursive.className}>
          <Navbar />
          {children}
          {/* <Footer/> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
